feat: support another .eaf format for mic ID identification
UAlbertaALTLab/recording-validation-interface pull request #141
Opened 2021-03-05 22:24 UTC by eddieantonio

Support extracting mic ID from `2017-05-18pm-US-Track_04`

2021-03-05 22:25 UTC, eddieantonio commented on validation/models.py
> +        help_text="The comment provided in the ELAN file", max_length=256, blank=True,
uh... black did this for me idk

2021-03-05 22:29 UTC, nienna73 commented on librecval/extract_phrases.py
> +                   -[UD]S   # upstairs/downstairs
Also `OFF` and `KCH`

2021-03-05 22:30 UTC, nienna73 requested changes
`get_mic_id` also needs to look for location codes `OFF` and `KCH`

2021-03-06 00:00 UTC, nienna73 requested changes
It's still upset with this format: `2017-04-20am-US_Recorded_Track1_001`
It might be the lack of '_', '  ', or '0' after "Track".

This issue isn't pressing, as in it doesn't affect production, so it can wait over the weekend.

2021-03-08 23:06 UTC, eddieantonio commented
> It's still upset with this format: `2017-04-20am-US_Recorded_Track1_001`
> It might be the lack of '_', ' ', or '0' after "Track".
> 
> This issue isn't pressing, as in it doesn't affect production, so it can wait over the weekend.

Um... just for posterity's sake: which "1" is the mic number? Is it the `Track1` or the `_001`?

2021-03-08 23:11 UTC, nienna73 commented
It's the `1` in `Track1`, I confirmed with the filesystem.

2021-03-12 18:16 UTC, nienna73 approved these changes
I think we finally got them all!

2021-03-12 20:37 UTC, merged